### ISSUE TITLE
Language translation of mod description in the game? 

### ISSUE THREAD

**Issue by 7wells** [andy5995/CartographyMode#1]
Hello!

I would like to understand how (for this 0ad mod, maybe applicalbe for other 0ad mods as well) a translation could be done?
E.g., this one shows "Allied Map" and the explanation "Toggle allied map (see what your allies see)."

How could this be translated to other languages, ideally depending on which language is set in the main game?

Thanks for your help and for all the great with this mod and other development!

**Comment by Jammyjamjamman** [comment]
Hi @7wells!

Translations go in a folder in the mod called [l10n](https://github.com/andy5995/CartographyMode/tree/trunk/a24/l10n). In there, you can see a file called [en_GB.public-gui-gamesetup-CartographyMode.po](https://github.com/andy5995/CartographyMode/blob/trunk/a24/l10n/en_GB.public-gui-gamesetup-CartographyMode.po).

I think the easiest way to add translations is to copy-paste the file I mentioned above, replacing 'en_GB' with the 2-letter code for your language e.g. `de.public-gui-gamesetup-CartographyMode.po`, for German. Then, in the new file, replace all the strings paired with `msgstr` with your translations. (`msgid` is the "identifier" for the translation.)
2 letter language codes can be found here: https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

Any translations would be very welcome :). Cheers.

**Comment by andy5995** [comment]
Hi, @7wells. There is information on the [0ad website for translators](https://trac.wildfiregames.com/wiki/Localization). Please let us know if you have any questions after reviewing their docs. Thank you for your interest.
