### ISSUE TITLE
Alpha 25

### ISSUE THREAD

**Issue by JustusAvramenko** [andy5995/CartographyMode#4]
Can this mod be rebased for Alpha 25? Alpha 24 version throws this error (and possibly others):

`ERROR: Error in timer: ReferenceError: g_GameAttributes is not defined getGameDescriptionList@gui/common/gamedescription_CartographyMode.js:9:6 getGameDescription@gui/common/gamedescription_CartographyMode.js:237:37 updateCaption@gui/gamesetup/Pages/GameSetupPage/Panels/GameDescription.js:51:62 updateTimers@gui/common/timer.js:61:8 onTick@gui/gamesetup/SetupWindow.js:105:3 @gui/gamesetup/SetupWindow.js:55:64`

@Jammyjamjamman

**Comment by Jammyjamjamman** [comment]
Working on an a25 version.

What version of a24 does this error happen on? I don't get this error using 0ad v24937-release (on manjaro linux).

**Comment by JustusAvramenko** [comment]
I am using the A25 development version, that's why I know it's currently incompatible with A25. :)

**Comment by JustusAvramenko** [comment]
I believe this A25 commit is relevant:

https://code.wildfiregames.com/D3243

**Comment by andy5995** [comment]
> Working on an a25 version.
> 
> What version of a24 does this error happen on? I don't get this error using 0ad v24937-release (on manjaro linux).

@Jammyjamjamman , I think @JustusAvramenko  meant the error happens when using the a24 version of the Cartography mod with version a25 of 0ad.

**Comment by Jammyjamjamman** [comment]
Ah that's why I couldn't find the bug xD... thanks!

**Comment by andy5995** [comment]
Gosh that seems like a lot of code in #7 ... I wonder if the mod shouldn't change anything, except for the cost of the upgrade... change to '0'? ;)

**Comment by Jammyjamjamman** [comment]
I am planning to reduce the amount of new code. That's just a basic knock-up to get the mod working.
Tbh a lot of that code exists purely for the UI option. If the allied view option was permanently on, the mod would be much smaller. Also, I think I've added a new feature where you can add an "allied view" property to map files, which has probably added more code. So map files can set "allied view".

**Comment by andy5995** [comment]
Completed by @Jammyjamjamman in https://github.com/andy5995/CartographyMode/commit/7353985062975bfead0aa70713273cd06d31209c
