### ISSUE TITLE
Allied Map -> Allied Vision

### ISSUE THREAD

**Issue by JustusAvramenko** [andy5995/CartographyMode#5]
I believe calling the game option "Allied Vision" instead of "Allied Map" would sound better to players.

**Comment by andy5995** [comment]
I agree. @JustusAvramenko , do you recommend changing that for the a24 version as well as changing it for future versions? Any idea how soon the a24 version of 0ad will become obsolete?

**Comment by JustusAvramenko** [comment]
I think just changing it for future versions should suffice. Feature Freeze for A25 is in one month, so I don't see the need to make updates to the A24 version.

**Comment by Jammyjamjamman** [comment]
This is added for the 0AD A25 version of this mod.
